#ifndef $INSERT_NAME$_h
#define $INSERT_NAME$_h

$INSERT_DEFINES$

typedef struct {
    double z[dim]; // Optimal z
    double s[n_s]; // Optimal s
    double lambda[n_s]; // Optimal lambda
} solution;

#ifdef CONF_MATLAB

void HMPC_ADMM(double *pointer_x0, double *pointer_xr, double *pointer_ur, double *u_opt, double *pointer_k, double *e_flag, double *z_opt, double *s_opt, double *lambda_opt);

#else

void HMPC_ADMM(double *pointer_x0, double *pointer_xr, double *pointer_ur, double *u_opt, int *pointer_k, int *e_flag, solution *sol);

#endif

#endif

void proj_SOC3(double *x, double alpha, double d);

// This code is generated by the Spcies toolbox: https://github.com/GepocUS/Spcies

