#include "mex.h"
#include "$C_CODE_NAME$.h"
#include <math.h>
#include <string.h>

// Matlab MEX function

void mexFunction(int nlhs, mxArray *plhs[],
                 int nrhs, const mxArray *prhs[]){

    // Variable declaration

    double *x0; // Local x0
    double *xr; // Local xr
    double *ur; // Local ur
    double *u_opt; // Local u_opt
    double *k; // Local k
    double *e_flag; // Local e_flag
    double *z1_opt; // Local z1_opt
    double *z2_opt; // Local z2_opt
    double *z3_opt; // Local z3_opt
    double *lambda_opt; // Local lambda_opt

    // Check inputs and outputs

    // Check number of inputs
    if(nrhs != 3){
        mexErrMsgIdAndTxt("Spcies:MPCT_EADMM:nrhs:number",
                          "Not enough inputs");
    }

    // Check number of outputs
    if(nlhs == 0){
        mexErrMsgIdAndTxt("Spcies:MPCT_EADMM:nlhs:number",
                          "At least one output required");
    }

    // Check that x0 is of the correct dimension
    if( !mxIsDouble(prhs[0]) || mxGetNumberOfElements(prhs[0]) != nn ){
        mexErrMsgIdAndTxt("Spcies:MPCT_EADMM:nrhs:x0",
                          "x0 must be of dimension nn");
    }
    // Check that xr is of the correct dimension
    if( !mxIsDouble(prhs[1]) || mxGetNumberOfElements(prhs[1]) != nn ){
        mexErrMsgIdAndTxt("Spcies:MPCT_EADMM:nrhs:xr",
                          "xr must be of dimension nn");
    }
    // Check that ur is of the correct dimension
    if( !mxIsDouble(prhs[2]) || mxGetNumberOfElements(prhs[2]) != mm ){
        mexErrMsgIdAndTxt("Spcies:MPCT_EADMM:nrhs:ur",
                          "ur must be of dimension mm");
    }

    // Read input data
    #if MX_HAS_INTERLEAVED_COMPLEX
    x0 = mxGetDoubles(prhs[0]);
    #else
    x0 = mxGetPr(prhs[0]);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    xr = mxGetDoubles(prhs[1]);
    #else
    xr = mxGetPr(prhs[1]);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    ur = mxGetDoubles(prhs[2]);
    #else
    ur = mxGetPr(prhs[2]);
    #endif

    // Prepare output data
    plhs[0] = mxCreateDoubleMatrix(mm, 1, mxREAL); // u_opt
    plhs[1] = mxCreateDoubleMatrix(1, 1, mxREAL); // k
    plhs[2] = mxCreateDoubleMatrix(1, 1, mxREAL); // e_flag

    const char *field_names[] = {"z1", "z2", "z3", "lambda"};
    plhs[3] = mxCreateStructMatrix(1, 1, 4, field_names);

    #if MX_HAS_INTERLEAVED_COMPLEX
    u_opt = mxGetDoubles(plhs[0]);
    #else
    u_opt = mxGetData(plhs[0]);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    k = mxGetDoubles(plhs[1]);
    #else
    k = mxGetData(plhs[1]);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    e_flag = mxGetDoubles(plhs[2]);
    #else
    e_flag = mxGetData(plhs[2]);
    #endif

    mxArray *z1, *z2, *z3, *lambda;
    z1 = mxCreateDoubleMatrix((NN+1)*nm, 1, mxREAL);
    z2 = mxCreateDoubleMatrix(nm, 1, mxREAL);
    z3 = mxCreateDoubleMatrix((NN+1)*nm, 1, mxREAL);
    lambda = mxCreateDoubleMatrix((NN+2)*nm + nn, 1, mxREAL);

    #if MX_HAS_INTERLEAVED_COMPLEX
    z1_opt = mxGetDoubles(z1);
    #else
    z1_opt = mxGetData(z1);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    z2_opt = mxGetDoubles(z2);
    #else
    z2_opt = mxGetData(z2);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    z3_opt = mxGetDoubles(z3);
    #else
    z3_opt = mxGetData(z3);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    lambda_opt = mxGetDoubles(lambda);
    #else
    lambda_opt = mxGetData(lambda);
    #endif

    mxSetField(plhs[3], 0, "z1", z1);
    mxSetField(plhs[3], 0, "z2", z2);
    mxSetField(plhs[3], 0, "z3", z3);
    mxSetField(plhs[3], 0, "lambda", lambda);

    // Call solver
    MPCT_EADMM(x0, xr, ur, u_opt, k, e_flag, z1_opt, z2_opt, z3_opt, lambda_opt);

}

// This code is generated by the Spcies toolbox: https://github.com/GepocUS/Spcies

