#include "mex.h"
#include "$C_CODE_NAME$.h"
#include <math.h>
#include <string.h>

// Matlab MEX function

void mexFunction(int nlhs, mxArray *plhs[],
                 int nrhs, const mxArray *prhs[]){

    // Variable declaration

    double *x0; // Local x0
    double *xr; // Local xr
    double *ur; // Local ur
    double *r; // Size of the ellipsoid
    double *u_opt; // Local u_opt
    double *k; // Local k
    double *e_flag; // Local e_flag
    double *z_opt; // Local z_opt
    double *s_opt; // Local v_opt
    double *z_hat_opt; // Local z_hat_opt
    double *s_hat_opt; // Local v_hat_opt
    double *lambda_opt; // Local lambda_opt
    double *mu_opt; // Local mu_opt

    // Check inputs and outputs

    // Check number of inputs
    if(nrhs != 4){
        mexErrMsgIdAndTxt("Spcies:ellipMPC:nrhs:number",
                          "Not enough inputs");
    }

    // Check number of outputs
    if(nlhs == 0){
        mexErrMsgIdAndTxt("Spcies:ellipMPC:nlhs:number",
                          "At least one output required");
    }

    // Check that x0 is of the correct dimension
    if( !mxIsDouble(prhs[0]) || mxGetNumberOfElements(prhs[0]) != nn ){
        mexErrMsgIdAndTxt("Spcies:ellipMPC:nrhs:x0",
                          "x0 must be of dimension nn");
    }
    // Check that xr is of the correct dimension
    if( !mxIsDouble(prhs[1]) || mxGetNumberOfElements(prhs[1]) != nn ){
        mexErrMsgIdAndTxt("Spcies:ellipMPC:nrhs:xr",
                          "xr must be of dimension nn");
    }
    // Check that ur is of the correct dimension
    if( !mxIsDouble(prhs[2]) || mxGetNumberOfElements(prhs[2]) != mm ){
        mexErrMsgIdAndTxt("Spcies:ellipMPC:nrhs:ur",
                          "ur must be of dimension mm");
    }
    // Check that r_ellip is of the correct dimension
    if( !mxIsDouble(prhs[3]) || mxGetNumberOfElements(prhs[3]) != 1 ){
        mexErrMsgIdAndTxt("Spcies:ellipMPC:nrhs:r",
                          "r must be a scalar");
    }

    // Read input data
    #if MX_HAS_INTERLEAVED_COMPLEX
    x0 = mxGetDoubles(prhs[0]);
    #else
    x0 = mxGetPr(prhs[0]);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    xr = mxGetDoubles(prhs[1]);
    #else
    xr = mxGetPr(prhs[1]);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    ur = mxGetDoubles(prhs[2]);
    #else
    ur = mxGetPr(prhs[2]);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    r = mxGetDoubles(prhs[3]);
    #else
    r = mxGetPr(prhs[3]);
    #endif

    // Prepare output data
    plhs[0] = mxCreateDoubleMatrix(mm, 1, mxREAL); // u_opt
    plhs[1] = mxCreateDoubleMatrix(1, 1, mxREAL); // k
    plhs[2] = mxCreateDoubleMatrix(1, 1, mxREAL); // e_flag

    const char *field_names[] = {"z", "s", "z_hat", "s_hat", "lambda", "mu"};
    plhs[3] = mxCreateStructMatrix(1, 1, 6, field_names);

    #if MX_HAS_INTERLEAVED_COMPLEX
    u_opt = mxGetDoubles(plhs[0]);
    #else
    u_opt = mxGetData(plhs[0]);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    k = mxGetDoubles(plhs[1]);
    #else
    k = mxGetData(plhs[1]);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    e_flag = mxGetDoubles(plhs[2]);
    #else
    e_flag = mxGetData(plhs[2]);
    #endif

    mxArray *z, *s, *z_hat, *s_hat, *lambda, *mu;
    z = mxCreateDoubleMatrix(dim, 1, mxREAL);
    s = mxCreateDoubleMatrix(n_s, 1, mxREAL);
    z_hat = mxCreateDoubleMatrix(dim, 1, mxREAL);
    s_hat = mxCreateDoubleMatrix(n_s, 1, mxREAL);
    lambda = mxCreateDoubleMatrix(dim, 1, mxREAL);
    mu = mxCreateDoubleMatrix(n_s, 1, mxREAL);

    #if MX_HAS_INTERLEAVED_COMPLEX
    z_opt = mxGetDoubles(z);
    #else
    z_opt = mxGetData(z);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    s_opt = mxGetDoubles(s);
    #else
    s_opt = mxGetData(s);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    z_hat_opt = mxGetDoubles(z_hat);
    #else
    z_hat_opt = mxGetData(z_hat);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    s_hat_opt = mxGetDoubles(s_hat);
    #else
    s_hat_opt = mxGetData(s_hat);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    lambda_opt = mxGetDoubles(lambda);
    #else
    lambda_opt = mxGetData(lambda);
    #endif

    #if MX_HAS_INTERLEAVED_COMPLEX
    mu_opt = mxGetDoubles(mu);
    #else
    mu_opt = mxGetData(mu);
    #endif

    mxSetField(plhs[3], 0, "z", z);
    mxSetField(plhs[3], 0, "s", s);
    mxSetField(plhs[3], 0, "z_hat", z_hat);
    mxSetField(plhs[3], 0, "s_hat", s_hat);
    mxSetField(plhs[3], 0, "lambda", lambda);
    mxSetField(plhs[3], 0, "mu", mu);

    // Call solver
    ellipMPC_ADMM_soc(x0, xr, ur, r, u_opt, k, e_flag, z_opt, s_opt, z_hat_opt, s_hat_opt, lambda_opt, mu_opt);

}

// This code is generated by the Spcies toolbox: https://github.com/GepocUS/Spcies

