%% add_notice
%
% Adds a notice to the provided text.
% The notice is a string that indicates that the file has
% been generated using the Spcies toolbox.
%
% This function is part of Spcies: https://github.com/GepocUS/Spcies
%

function text = add_notice(text, options)

    if strcmp(options.platform, 'C')
        text = strcat(text, '\n\n// This code is generated by the Spcies toolbox: https://github.com/GepocUS/Spcies\n');

    elseif strcmp(options.platform, 'Arduino')
        text = strcat(text, '\n\n// This code is generated by the Spcies toolbox: https://github.com/GepocUS/Spcies\n');

    end
    
end

