#ifndef $INSERT_NAME$_h
#define $INSERT_NAME$_h

$INSERT_DEFINES$

typedef struct {
    double z[NN*nm]; // Optimal z
    double v[NN*nm]; // Optimal v
    double lambda[NN*nm]; // Optimal lambda
} solution_MPCT_ess;

#ifdef CONF_MATLAB

void MPCT_ess_ADMM(double *pointer_x0, double *pointer_xr, double *pointer_ur, double *u_opt, double *pointer_k, double *e_flag, double *z_opt, double *v_opt, double *lambda_opt);

#else

void MPCT_ess_ADMM(double *pointer_x0, double *pointer_xr, double *pointer_ur, double *u_opt, int *pointer_k, int *e_flag, solution_MPCT_ess *sol);

#endif

#endif

// This code is generated by the Spcies toolbox: https://github.com/GepocUS/Spcies

