

function text = add_notice(text, options)

    if strcmp(options.platform, 'C')
        text = strcat(text, '\n\n// This code is generated by the Spcies toolbox: https://github.com/GepocUS/Spcies\n');
    end
    
end
